CREATE TABLE IF NOT EXISTS qotp_meta (
 id TINYINT UNSIGNED PRIMARY KEY, schema_version INT UNSIGNED NOT NULL, installed_at VARCHAR(27) CHARACTER SET ascii NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS qotp_users (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, username VARCHAR(64) NOT NULL UNIQUE,
 password_hash VARCHAR(255) CHARACTER SET ascii NOT NULL, must_change_password TINYINT UNSIGNED NOT NULL DEFAULT 0,
 created_at VARCHAR(27) CHARACTER SET ascii NOT NULL, updated_at VARCHAR(27) CHARACTER SET ascii NOT NULL,
 last_login_at VARCHAR(27) CHARACTER SET ascii NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS qotp_sessions (
 token_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin PRIMARY KEY,
 user_id BIGINT UNSIGNED NOT NULL, csrf_token CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 created_at VARCHAR(27) CHARACTER SET ascii NOT NULL, expires_at VARCHAR(27) CHARACTER SET ascii NOT NULL,
 KEY (expires_at), KEY (user_id), FOREIGN KEY (user_id) REFERENCES qotp_users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS qotp_login_failures (
 ip_address VARCHAR(45) CHARACTER SET ascii PRIMARY KEY, attempts INT UNSIGNED NOT NULL DEFAULT 0,
 updated_at VARCHAR(27) CHARACTER SET ascii NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS qotp_blocked_ips (
 ip_address VARCHAR(45) CHARACTER SET ascii PRIMARY KEY, created_at VARCHAR(27) CHARACTER SET ascii NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS qotp_reauth_failures (
 user_id BIGINT UNSIGNED PRIMARY KEY, attempts INT UNSIGNED NOT NULL DEFAULT 0,
 blocked_until VARCHAR(27) CHARACTER SET ascii NOT NULL DEFAULT '',
 FOREIGN KEY (user_id) REFERENCES qotp_users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS qotp_app_settings (
 id TINYINT UNSIGNED PRIMARY KEY, default_domain VARCHAR(253) CHARACTER SET ascii NOT NULL,
 generator_type VARCHAR(32) CHARACTER SET ascii NOT NULL, default_prefix VARCHAR(55) CHARACTER SET ascii NOT NULL DEFAULT '',
 default_domains TEXT NOT NULL, auto_fill_watch TINYINT UNSIGNED NOT NULL DEFAULT 1,
 auto_start_watch TINYINT UNSIGNED NOT NULL DEFAULT 0, appearance VARCHAR(8) CHARACTER SET ascii NOT NULL DEFAULT 'system',
 updated_at VARCHAR(27) CHARACTER SET ascii NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS qotp_generated_emails (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 email VARCHAR(254) CHARACTER SET ascii COLLATE ascii_bin NOT NULL UNIQUE,
 local_part VARCHAR(64) CHARACTER SET ascii NOT NULL, domain VARCHAR(253) CHARACTER SET ascii NOT NULL,
 generator_type VARCHAR(32) CHARACTER SET ascii NOT NULL, created_at VARCHAR(27) CHARACTER SET ascii NOT NULL,
 KEY (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS qotp_mail_config (
 id TINYINT UNSIGNED PRIMARY KEY, provider VARCHAR(8) CHARACTER SET ascii NOT NULL,
 host VARCHAR(253) CHARACTER SET ascii NOT NULL, port INT UNSIGNED NOT NULL,
 username VARCHAR(254) NOT NULL, folder VARCHAR(256) NOT NULL, password_encrypted TEXT NOT NULL,
 updated_at VARCHAR(27) CHARACTER SET ascii NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS qotp_messages (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, source_key CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL UNIQUE,
 recipient VARCHAR(254) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 sender TEXT NOT NULL, subject TEXT NOT NULL, body_text MEDIUMTEXT NOT NULL,
 otp VARCHAR(8) CHARACTER SET ascii NOT NULL DEFAULT '', received_at VARCHAR(27) CHARACTER SET ascii NOT NULL,
 KEY recipient_received_idx (recipient,received_at,id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
